import { faChevronRight } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { Component } from "react";
import { Accordion, Card, Col, Row, Table } from "react-bootstrap";
import './faq.css'
import { scroller } from "react-scroll";
import ContactUs from "../contact-us/ContactUs";
import Header from "../header/Header";

class FAQ extends Component {

  constructor(props) {
    super(props);
    this.state = {
      activeFaq: 0,
      showContactUs: false,
    }
  }

  openContactUs = () => {
    this.setState({showContactUs: true})
  }

  handleContactUsClose = () => {
    this.setState({showContactUs: false})
  }

  handleScroll = () => {
    this.props.history.push({
      pathname: '/',
    })
    setTimeout(() => {
      scroller.scrollTo('product', {
        duration: 800,
        delay: 5,
        smooth: 'easeInOutQuart',
        offset: -90
      })
    }, 400)
  }

  handlePilotScroll = () => {
    this.props.history.push({
      pathname: '/',
    })
    setTimeout(() => {
      scroller.scrollTo('pilot', {
        duration: 800,
        delay: 5,
        smooth: 'easeInOutQuart',
        offset: -90
      })
    }, 400)
  }

  scrollToFaq = () => {
    this.setState({activeFaq: '7'});
    setTimeout(() => {
      scroller.scrollTo('corporate-actions', {
        duration: 800,
        delay: 5,
        smooth: 'easeInOutQuart',
        offset: -90
      })
    }, 400)
  }


  setActiveAccordion = (index) => {
    this.setState({activeFaq: index})
  }

  render() {
    return (
      <section>
        <Header />
        <section className={'pb-5'}>
          <Row>
            <Col>
              <h2 className={'pt-5 pb-3'}>FAQs</h2>
            </Col>
          </Row>
          <Row>
            <Col sm={12} className={'pl-5 pr-5'}>
              <Accordion
                className={'faq-accordion'}
                activeKey={this.state.activeFaq}
                onSelect={(event) => this.setActiveAccordion(event)}>
                <Card className={'mb-3'}>
                  <Accordion.Toggle as={Card.Header} eventKey={'0'}>
                    {this.state.activeFaq === '0' ? (
                      <strong className={'mr-3 active-accordion'} >|</strong>
                    ) : (
                      <FontAwesomeIcon icon={faChevronRight} className={'mr-2'} color={'green'} />
                    )}
                    What is Mark?
                  </Accordion.Toggle>
                  <Accordion.Collapse eventKey={'0'}>
                    <Card.Body>
                      Mark is our proprietary, fully automated signal engine that assist US equity asset managers in the buy/sell decision
                      making process across intraday, intraweek, and intramonth durations.<br/>
                      See <strong className={'text-success'} role={"button"} onClick={this.handleScroll}>Product Use Cases</strong>.
                      Mark was developed by Intramark Inc. (Intramark), a fintech data firm.
                    </Card.Body>
                  </Accordion.Collapse>
                </Card>
                <Card className={'mb-3'}>
                  <Accordion.Toggle as={Card.Header} eventKey={'1'}>
                    {this.state.activeFaq === '1' ? (
                      <strong className={'mr-3 active-accordion'} >|</strong>
                    ) : (
                      <FontAwesomeIcon icon={faChevronRight} className={'mr-2'} color={'green'} />
                    )}
                    How are Mark buy/sell signals generated?
                  </Accordion.Toggle>
                  <Accordion.Collapse eventKey={'1'}>
                    <Card.Body>
                      Mark buy and sell signals, or “Marks”, are generated by our proprietary, fully automated signal engine. The core of the Mark
                      signal engine is, what we believe to be, a novel trend reversal strategy for US equities. We employ
                      computer processing to derive non-linear outputs to estimate when it is most probable that an
                      equity security has reached its lower limit or upper limit across intraday, intraweek, and intramonth
                      durations. Mark signal quality does not depend on curve-fitting or market conditions.
                    </Card.Body>
                  </Accordion.Collapse>
                </Card>
                <Card className={'mb-3'}>
                  <Accordion.Toggle as={Card.Header} eventKey={'10'}>
                    {this.state.activeFaq === '10' ? (
                      <strong className={'mr-3 active-accordion'} >|</strong>
                    ) : (
                      <FontAwesomeIcon icon={faChevronRight} className={'mr-2'} color={'green'} />
                    )}
                    What do you mean by the Mark signal engine is "fully automated"?
                  </Accordion.Toggle>
                  <Accordion.Collapse eventKey={'10'}>
                    <Card.Body>
                      The proprietary Mark signal
                      engine generates Marks for US equities based on defined parameters and real-time market
                      information. Defined parameters may change over time as Intramark makes continuous
                      improvements to the proprietary Mark signal engine to improve Mark signal quality. Intramark
                      makes best efforts to halt Mark deliveries for equities undergoing certain corporate actions until
                      necessary adjustments to internal data and processes are made. See FAQ
                      <strong role={'button'} onClick={this.scrollToFaq} className={'text-success'}>“How are corporate
                        actions managed in connection to Marks?”</strong>. Apart from the above, human judgement or skill is not
                      introduced in generating Marks.
                    </Card.Body>
                  </Accordion.Collapse>
                </Card>
                <Card className={'mb-3'}>
                  <Accordion.Toggle as={Card.Header} eventKey={'2'}>
                    {this.state.activeFaq === '2' ? (
                      <strong className={'mr-3 active-accordion'} >|</strong>
                    ) : (
                      <FontAwesomeIcon icon={faChevronRight} className={'mr-2'} color={'green'} />
                    )}
                    How have Marks performed?
                  </Accordion.Toggle>
                  <Accordion.Collapse eventKey={'2'}>
                    <Card.Body>
                      <div>
                        <span className={'underline'}>Actual</span>:
                        <div>
                          Refer to the Mark history library for performance stats on the buy and sell Marks delivered to
                          customers to date. You must <strong className={'text-success'} role={"button"} onClick={this.handlePilotScroll}>Join Free Pilot</strong> for access to the Mark history library.
                        </div>
                      </div>
                      <div className={'mt-3'}>
                        <span className={'underline'}>Back-test</span>:
                        <div>
                          Marks are back-tested over at least 5-10 years for each equity security covered. Aggregate stats on Mark
                          back-test results for an equity security covered is available upon request.
                        </div>
                      </div>
                    </Card.Body>
                  </Accordion.Collapse>
                </Card>
                <Card className={'mb-3'}>
                  <Accordion.Toggle as={Card.Header} eventKey={'3'}>
                    {this.state.activeFaq === '3' ? (
                      <strong className={'mr-3 active-accordion'} >|</strong>
                    ) : (
                      <FontAwesomeIcon icon={faChevronRight} className={'mr-2'} color={'green'} />
                    )}
                    What are the use cases for Marks?
                  </Accordion.Toggle>
                  <Accordion.Collapse eventKey={'3'}>
                    <Card.Body>
                      <Row>
                        <Col sm={12}>
                          Asset managers use Marks to assist with equity buy or sell decisions across intraday, intraweek, and
                          intramonth durations. Marks supplement decisions around, but not limited to:
                        </Col>
                        <Col sm={12} className={'terms-of-use pl-5 pr-5 pt-2'}>
                          <FontAwesomeIcon icon={faChevronRight} color={'green'} className={'mr-2'} />
                          <span>price discovery</span>
                        </Col>
                        <Col sm={12} className={'terms-of-use pl-5 pr-5 pt-2'}>
                          <FontAwesomeIcon icon={faChevronRight} color={'green'} className={'mr-2'} />
                          <span>covered call writes</span>
                        </Col>
                        <Col sm={12} className={'terms-of-use pl-5 pr-5 pt-2'}>
                          <FontAwesomeIcon icon={faChevronRight} color={'green'} className={'mr-2'} />
                          <span>momentum indications</span>
                        </Col>
                        <Col sm={12} className={'terms-of-use pl-5 pr-5 pt-2'}>
                          <FontAwesomeIcon icon={faChevronRight} color={'green'} className={'mr-2'} />
                          <span>risk management (stop-loss)</span>
                        </Col>
                        <Col sm={12} className={'terms-of-use pl-5 pr-5 pt-2'}>
                          <FontAwesomeIcon icon={faChevronRight} color={'green'} className={'mr-2'} />
                          <span>position rebalances and/or tactical shifts</span>
                        </Col>
                      </Row>
                      <Row className={'mt-3'}>
                        <Col sm={12}>
                          See <strong className={'text-success'} role={"button"} onClick={this.handleScroll}>Product Use Cases</strong> for more use cases and examples.
                        </Col>
                      </Row>
                    </Card.Body>
                  </Accordion.Collapse>
                </Card>
                <Card className={'mb-3'}>
                  <Accordion.Toggle as={Card.Header} eventKey={'4'}>
                    {this.state.activeFaq === '4' ? (
                      <strong className={'mr-3 active-accordion'} >|</strong>
                    ) : (
                      <FontAwesomeIcon icon={faChevronRight} className={'mr-2'} color={'green'} />
                    )}
                    How many US equities do you provide Marks?
                  </Accordion.Toggle>
                  <Accordion.Collapse eventKey={'4'}>
                    <Card.Body>
                      During the <strong className={'text-success'} role={"button"} onClick={this.handlePilotScroll}> Free Pilot</strong>, we provide intraday, intraweek, and intramonth Marks for up to 10 US stocks
                      and/or ETFs. The live Mark product will support Marks for over 1,000 US stocks and over 50 US ETFs
                      across large, medium, and small-caps. We plan to launch the live Mark product by end of Q3 2022.
                    </Card.Body>
                  </Accordion.Collapse>
                </Card>
                <Card className={'mb-3'}>
                  <Accordion.Toggle as={Card.Header} eventKey={'5'}>
                    {this.state.activeFaq === '5' ? (
                      <strong className={'mr-3 active-accordion'} >|</strong>
                    ) : (
                      <FontAwesomeIcon icon={faChevronRight} className={'mr-2'} color={'green'} />
                    )}
                    How frequently do buy or sell Marks occur for a given equity security?
                  </Accordion.Toggle>
                  <Accordion.Collapse eventKey={'5'}>
                    <Card.Body>
                      Frequency of buy or sell Marks vary by equity security. As an estimate, you can expect:
                      <Table bordered responsive={'sm'} className={'mt-3'}>
                        <thead>
                        <tr>
                          <th>Mark type</th>
                          <th>Buy Mark delivery frequency</th>
                          <th>Sell Mark delivery frequency</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                          <td>Intraday</td>
                          <td>71 trading days in year</td>
                          <td>37 trading days in year</td>
                        </tr>
                        <tr>
                          <td>Intraweek</td>
                          <td>18 weeks in year</td>
                          <td>9 weeks in year</td>
                        </tr>
                        <tr>
                          <td>Intramonth</td>
                          <td>3 months in year</td>
                          <td>1 month in year</td>
                        </tr>
                        </tbody>
                      </Table>
                      <div className={'mt-3'}>
                        <strong className={'text-success'} role={"button"} onClick={this.openContactUs}>Contact Us</strong> for estimates on specific equity securities covered.
                      </div>
                    </Card.Body>
                  </Accordion.Collapse>
                </Card>
                <Card className={'mb-3'}>
                  <Accordion.Toggle as={Card.Header} eventKey={'6'}>
                    {this.state.activeFaq === '6' ? (
                      <strong className={'mr-3 active-accordion'} >|</strong>
                    ) : (
                      <FontAwesomeIcon icon={faChevronRight} className={'mr-2'} color={'green'} />
                    )}
                    Do you provide Marks for durations other than intraday, intraweek, and intramonth?
                  </Accordion.Toggle>
                  <Accordion.Collapse eventKey={'6'}>
                    <Card.Body>
                      By Q1 2023, we plan to support Mark orders for custom dates and possibly for durations beyond one
                      month. Until then, we provide Marks for intraday and calendar week and month durations.
                    </Card.Body>
                  </Accordion.Collapse>
                </Card>
                <Card className={'mb-3 corporate-actions'}>
                  <Accordion.Toggle as={Card.Header} eventKey={'7'}>
                    {this.state.activeFaq === '7' ? (
                      <strong className={'mr-3 active-accordion'} >|</strong>
                    ) : (
                      <FontAwesomeIcon icon={faChevronRight} className={'mr-2'} color={'green'} />
                    )}
                    How are corporate actions managed in connection to Marks?
                  </Accordion.Toggle>
                  <Accordion.Collapse eventKey={'7'}>
                    <Card.Body>
                      <Row>
                        <Col sm={12}>
                          A corporate action is an event - agreed upon by a company's board of directors and authorized by its
                          shareholders - that causes material change to the company's securities. Intramark makes best
                          efforts to halt Mark deliveries for equities undergoing certain corporate actions until necessary adjustments to internal
                          data and processes are made. Corporate actions that may result in a halt in Mark deliveries for impacted
                          equities include, but are not limited to:
                        </Col>
                        <Col sm={12} className={'terms-of-use pl-5 pr-5 pt-2'}>
                          <FontAwesomeIcon icon={faChevronRight} color={'green'} className={'mr-2'} />
                          <span>Mergers and acquisitions</span>
                        </Col>
                        <Col sm={12} className={'terms-of-use pl-5 pr-5 pt-2'}>
                          <FontAwesomeIcon icon={faChevronRight} color={'green'} className={'mr-2'} />
                          <span>Stock splits</span>
                        </Col>
                        <Col sm={12} className={'terms-of-use pl-5 pr-5 pt-2'}>
                          <FontAwesomeIcon icon={faChevronRight} color={'green'} className={'mr-2'} />
                          <span>Symbol/name change</span>
                        </Col>
                      </Row>
                      <Row className={'mt-3'}>
                        <Col sm={12}>
                          Generally, regularly scheduled dividends may not result in a halt in Mark deliveries.
                        </Col>
                      </Row>
                    </Card.Body>
                  </Accordion.Collapse>
                </Card>
                <Card className={'mb-3'}>
                  <Accordion.Toggle as={Card.Header} eventKey={'8'}>
                    {this.state.activeFaq === '8' ? (
                      <strong className={'mr-3 active-accordion'} >|</strong>
                    ) : (
                      <FontAwesomeIcon icon={faChevronRight} className={'mr-2'} color={'green'} />
                    )}
                    Does Intramark trade on Marks?
                  </Accordion.Toggle>
                  <Accordion.Collapse eventKey={'8'}>
                    <Card.Body>
                      <Row>
                        <Col sm={12}>
                          Intramark, its directors, its officers, its agents, and its employees do not trade on Marks that are ordered
                          by or delivered to customers. Intramark may trade its own capital on Marks that have not been ordered
                          by or delivered to customers.
                        </Col>
                      </Row>
                    </Card.Body>
                  </Accordion.Collapse>
                </Card>
                <Card className={'mb-3'}>
                  <Accordion.Toggle as={Card.Header} eventKey={'11'}>
                    {this.state.activeFaq === '11' ? (
                      <strong className={'mr-3 active-accordion'} >|</strong>
                    ) : (
                      <FontAwesomeIcon icon={faChevronRight} className={'mr-2'} color={'green'} />
                    )}
                    Why does Intramark sell Marks rather than keep all Marks proprietary?
                  </Accordion.Toggle>
                  <Accordion.Collapse eventKey={'11'}>
                    <Card.Body>
                      <Row>
                        <Col sm={12}>
                          We plan to launch the live Mark product by end of Q3 2022, whereby we will have the capacity to generate Marks for over 2,000 stocks and ETFs; these are more Marks than Intramark
                          could utilize for any purpose in the foreseeable future. Intramark, its directors, its
                          officers, its agents, and its employees do not trade on Marks that are ordered by or delivered to
                          customers. Intramark may trade its own capital on Marks that have not been ordered by or
                          delivered to customers.
                        </Col>
                      </Row>
                    </Card.Body>
                  </Accordion.Collapse>
                </Card>
                <Card className={'mb-3'}>
                  <Accordion.Toggle as={Card.Header} eventKey={'9'}>
                    {this.state.activeFaq === '9' ? (
                      <strong className={'mr-3 active-accordion'} >|</strong>
                    ) : (
                      <FontAwesomeIcon icon={faChevronRight} className={'mr-2'} color={'green'} />
                    )}
                    What is the purpose of the Free Pilot?
                  </Accordion.Toggle>
                  <Accordion.Collapse eventKey={'9'}>
                    <Card.Body>
                      <Row>
                        <Col sm={12}>
                          The <strong className={'text-success'} role={"button"} onClick={this.handlePilotScroll}>Free Pilot</strong> (no payment info required) gives early adopters an opportunity to experience the Mark
                          product first-hand. Further, the <strong className={'text-success'} role={"button"} onClick={this.handlePilotScroll}>Free Pilot</strong> gives us an opportunity to collect feedback to further develop
                          the Mark product. We plan to launch the live Mark product by end of Q3 2022.
                        </Col>
                      </Row>
                    </Card.Body>
                  </Accordion.Collapse>
                </Card>
              </Accordion>
            </Col>
          </Row>
        </section>
        {this.state.showContactUs && (
          <ContactUs showContactUs={this.state.showContactUs} handleClose={this.handleContactUsClose} />
        )}
      </section>
    );
  }

}

export default FAQ;
